### ISSUE TITLE
样式上的一些小问题

### ISSUE THREAD

**Issue by Miaonster** [nihgwu/Nevermore#1]
我贴几个样式上的截图：
1. Mac 上服务器名称这一栏的向右的箭头是不怎么对，一是图标位置没有居中对齐，一是旁边有白边
   ![4153a1ee-3ce9-43ab-a2ce-58ff07c78276](https://cloud.githubusercontent.com/assets/1927546/4284115/7c54253c-3d78-11e4-8e8f-f2fbfe198d7b.png)
2. Mac 上服务器列表中服务器的名称有 2px margin，不知道是否故意这么设计的
   ![image](https://cloud.githubusercontent.com/assets/1927546/4284118/88a3c806-3d78-11e4-9dd3-f16b3afeb22a.png)
3. README 的截图中加密方式没有对齐，这个应该是 Windows 上的吧，Mac 上倒是 OK
   ![image](https://cloud.githubusercontent.com/assets/1927546/4284141/bb506de0-3d78-11e4-8c91-b937f0c0aeff.png)

**Comment by nihgwu** [comment]
1. 因为我没用用图标，就是 &gt; 白边是我故意留的。。不过貌似多了1px
2. 太细致了吧。。
3. 对的，Win Mac不同
