### ISSUE TITLE
你好，我借鉴你的思路来做一个测试的，不过一直保存

### ISSUE THREAD

**Issue by joveqiao** [nihgwu/Nevermore#5]
![image](https://cloud.githubusercontent.com/assets/5110950/6425242/7d73dc22-bf5b-11e4-98c7-c65136fb6075.png)

调试报这个错误，我代码：
![image](https://cloud.githubusercontent.com/assets/5110950/6425264/2f2eb7de-bf5c-11e4-851e-e5eb62e2a8f1.png)

有地方不对吗？已经NPM了。。

**Comment by nihgwu** [comment]
会不会是端口被占用了

**Comment by joveqiao** [comment]
不应该啊，我没有开其他的代理软件的。

**Comment by joveqiao** [comment]
直接下载这个东西使用都不能代理成功。。。。 我 win10
